### ISSUE TITLE
Backend - Remove the /api/permissions/user-roles-list endpoint

### ISSUE THREAD

**Issue by mrsbluerose** [savvato-software/tribe-app-backend#238]
This is a duplicate of `/api/permissions/user-roles`. 

Verify that on the frontend, we are not calling user-roles-list. If we are, change the reference to user-roles. Then remove the user-roles-list endpoint from the backend.

Linked Frontend Issue: https://github.com/savvato-software/tribe-app-frontend/issues/123

Imported from Jira:
[https://mockprogrammingjob.atlassian.net/browse/TRIB-171?atlOrigin=eyJpIjoiZjVlNzRlMDdiNmZkNDAyMTk1ZGRjZTYzMmI4OTA0OGEiLCJwIjoiaiJ9](https://mockprogrammingjob.atlassian.net/browse/TRIB-171?atlOrigin=eyJpIjoiZjVlNzRlMDdiNmZkNDAyMTk1ZGRjZTYzMmI4OTA0OGEiLCJwIjoiaiJ9)

**Comment by haxwell** [comment]
They're not actually duplicate.. one is returning from the user-roles map, and the other user-roles table.
