### ISSUE TITLE
Python script to push recent payments to the ERC 20 script

### ISSUE THREAD

**Issue by mrsbluerose** [savvato-software/tribe-app-backend#245]
Needs to keep track of the last git commit hash used to calculate the totals it is pushing for. If we are not past that hash, on the main branch, then the script should not run.

Imported from Jira:
[https://mockprogrammingjob.atlassian.net/browse/TRIB-39?atlOrigin=eyJpIjoiMDdlY2M0Y2VhYzk1NDBkOWE0ZGU4OThlODlkZGU2YzEiLCJwIjoiaiJ9](https://mockprogrammingjob.atlassian.net/browse/TRIB-39?atlOrigin=eyJpIjoiMDdlY2M0Y2VhYzk1NDBkOWE0ZGU4OThlODlkZGU2YzEiLCJwIjoiaiJ9)

**Comment by haxwell** [comment]
Closing this.. we're not worried about payments for a while.
