### ISSUE TITLE
Python script to calculate token payments

### ISSUE THREAD

**Issue by mrsbluerose** [savvato-software/tribe-app-backend#246]
https://github.com/savvato-software/savvato-residualsConnect your Github account 

Imported from Jira:
[https://mockprogrammingjob.atlassian.net/browse/TRIB-38?atlOrigin=eyJpIjoiNmM1YjhlZTE3ZmJiNDNiNmI1Y2VmMzM3OTM1NWZmNDciLCJwIjoiaiJ9](https://mockprogrammingjob.atlassian.net/browse/TRIB-38?atlOrigin=eyJpIjoiNmM1YjhlZTE3ZmJiNDNiNmI1Y2VmMzM3OTM1NWZmNDciLCJwIjoiaiJ9)

**Comment by haxwell** [comment]
Closing.. payments are not planned for now.
