### ISSUE TITLE
Test the Savvato ERC 20 contract on an ETH test net

### ISSUE THREAD

**Issue by mrsbluerose** [savvato-software/tribe-app-backend#247]
[GitHub - savvato-software/savvato-erc20-contracts: Home of the Savvato ERC 20 contract](https://github.com/savvato-software/savvato-erc20-contracts)

Imported from Jira:
[https://mockprogrammingjob.atlassian.net/browse/TRIB-37?atlOrigin=eyJpIjoiOGViOTBjOGVhM2NjNDg1N2JkODk5ZTk3M2QzZjYzMjUiLCJwIjoiaiJ9](https://mockprogrammingjob.atlassian.net/browse/TRIB-37?atlOrigin=eyJpIjoiOGViOTBjOGVhM2NjNDg1N2JkODk5ZTk3M2QzZjYzMjUiLCJwIjoiaiJ9)

**Comment by haxwell** [comment]
Closing. not doing payments for a while.
